# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagedeals', '0001_squashed_0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='packagedeal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='packagedeals.PackageDeal'),
        ),
    ]
