# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_packagedeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Hotspot', 'verbose_name_plural': 'Hotspots'},
        ),
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(default='destinations/hotspots/pin_location.png', upload_to='destinations/hotspots'),
        ),
        migrations.AddField(
            model_name='destination',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
