# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20161003_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
