# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160826_0617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([('lastname', 'firstname')]),
        ),
    ]
