# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160913_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('SU', 'Superuser'), ('C', 'Customer'), ('D', 'Driver')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='driverdetails',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set([]),
        ),
    ]
