# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160919_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='driverdetails',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
