# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160919_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='profile_pic',
            field=models.ImageField(default='media/profilepics/default.png', upload_to='media/profilepics/'),
        ),
    ]
