# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customerdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='debtUSD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
