# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20161113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='profile_pic',
            field=models.ImageField(default='profilepics/default.png', upload_to='profilepics/'),
        ),
    ]
