# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20161113_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='debtUSD',
            field=models.FloatField(default=0),
        ),
    ]
