# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlymorningprofit',
            options={'verbose_name': 'EarlyMorning profitss'},
        ),
    ]
