# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afternoon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='earlyafternoon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='earlymorning',
            name='id',
        ),
        migrations.RemoveField(
            model_name='evening',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lateafternoon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='morning',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nighttime',
            name='id',
        ),
        migrations.AlterField(
            model_name='afternoon',
            name='name',
            field=models.CharField(default='Afternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='afternoonprofit',
            name='nameProfit',
            field=models.CharField(default='Afternoon', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlyafternoon',
            name='name',
            field=models.CharField(default='EarlyAfternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='earlyafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyAfternoon', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlymorning',
            name='name',
            field=models.CharField(default='EarlyMorning', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='earlymorningprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyMorning', max_length=100),
        ),
        migrations.AlterField(
            model_name='evening',
            name='name',
            field=models.CharField(default='Evening', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eveningprofit',
            name='nameProfit',
            field=models.CharField(default='Evening', max_length=100),
        ),
        migrations.AlterField(
            model_name='lateafternoon',
            name='name',
            field=models.CharField(default='LateAfternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lateafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='LateAfternoon', max_length=100),
        ),
        migrations.AlterField(
            model_name='morning',
            name='name',
            field=models.CharField(default='Morning', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='morningprofit',
            name='nameProfit',
            field=models.CharField(default='Morning', max_length=100),
        ),
        migrations.AlterField(
            model_name='nighttime',
            name='name',
            field=models.CharField(default='Nighttime', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nighttimeprofit',
            name='nameProfit',
            field=models.CharField(default='Nighttime', max_length=100),
        ),
    ]
