# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20161113_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoon',
            name='name',
            field=models.CharField(default='Afternoon base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonprofit',
            name='nameProfit',
            field=models.CharField(default='Afternoon profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlyafternoon',
            name='name',
            field=models.CharField(default='EarlyAfternoon base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlyafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyAfternoon profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlymorning',
            name='name',
            field=models.CharField(default='EarlyMorning base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='earlymorningprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyMorning profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='evening',
            name='name',
            field=models.CharField(default='Evening base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveningprofit',
            name='nameProfit',
            field=models.CharField(default='Evening profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='lateafternoon',
            name='name',
            field=models.CharField(default='LateAfternoon base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='lateafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='LateAfternoon profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='morning',
            name='name',
            field=models.CharField(default='Morning base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='morningprofit',
            name='nameProfit',
            field=models.CharField(default='Morning profit', max_length=100),
        ),
        migrations.AlterField(
            model_name='nighttime',
            name='name',
            field=models.CharField(default='Nighttime base price', max_length=100),
        ),
        migrations.AlterField(
            model_name='nighttimeprofit',
            name='nameProfit',
            field=models.CharField(default='Nighttime profit', max_length=100),
        ),
    ]
