# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20161115_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoonprofit',
            name='nameProfit',
            field=models.CharField(default='Afternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='afternoonprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.Afternoon'),
        ),
        migrations.AlterField(
            model_name='earlyafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyAfternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='earlyafternoonprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.EarlyAfternoon'),
        ),
        migrations.AlterField(
            model_name='earlymorningprofit',
            name='nameProfit',
            field=models.CharField(default='EarlyMorning', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='earlymorningprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.EarlyMorning'),
        ),
        migrations.AlterField(
            model_name='eveningprofit',
            name='nameProfit',
            field=models.CharField(default='Evening', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eveningprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.Evening'),
        ),
        migrations.AlterField(
            model_name='lateafternoonprofit',
            name='nameProfit',
            field=models.CharField(default='LateAfternoon', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lateafternoonprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.LateAfternoon'),
        ),
        migrations.AlterField(
            model_name='morningprofit',
            name='nameProfit',
            field=models.CharField(default='Morning', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='morningprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.Morning'),
        ),
        migrations.AlterField(
            model_name='nighttimeprofit',
            name='nameProfit',
            field=models.CharField(default='Nighttime', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nighttimeprofit',
            name='related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.Nighttime'),
        ),
    ]
