# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'packagedeals', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDeal',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('header_image', models.ImageField(default='settings.MEDIA_ROOT/packagedeals/headers/pin_location.png', upload_to='settings.MEDIA_ROOT/packagedeals/headers/')),
                ('description', models.CharField(default='', max_length=1000)),
                ('price', models.FloatField(default=0.0)),
                ('time_first_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_first_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_second_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_second_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickuppoint', models.CharField(default='0000.0000', max_length=15)),
                ('dropoffpoint', models.CharField(default='0000.0000', max_length=15)),
            ],
            options={
                'verbose_name': 'Packagedeal',
                'verbose_name_plural': 'Packagedeals',
            },
        ),
    ]
