# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedeals', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedeal',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
