# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedeals', '0002_auto_20160913_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedeal',
            name='header_image',
            field=models.ImageField(default='settings.MEDIA_ROOT/packagedeals/headers/pin_location.png', upload_to='settings.STATIC_ROOT/packagedeals/headers/'),
        ),
    ]
