# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedeals', '0005_auto_20161113_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedeal',
            name='header_image',
            field=models.ImageField(default='packagedeals/headers/hillary.jpg', upload_to='packagedeals/headers'),
        ),
    ]
