# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtt_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtt_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPoint', models.CharField(default=b'unknown', max_length=30)),
                ('dropOffPoint', models.CharField(default=b'unknown', max_length=30)),
                ('dateTimeTrip', models.DateTimeField()),
                ('timeConsumed', models.TimeField()),
                ('tripOrderDateTime', models.DateTimeField()),
                ('tripStartDateTime', models.DateTimeField()),
                ('etaArrival', models.TimeField()),
                ('etaTrip', models.TimeField()),
                ('etaKM', models.FloatField()),
                ('feedbackDriver', models.TextField(max_length=1000)),
                ('feedbackCustomer', models.TextField(max_length=1000)),
                ('ratingDriver', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('ratingCustomer', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='fare',
            name='tripsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.TripSession'),
        ),
    ]
