# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='tripsession',
            options={'verbose_name': 'Tripsession', 'verbose_name_plural': 'Tripsessions'},
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='ratingCustomer',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='ratingDriver',
        ),
    ]
