# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_triprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsession',
            old_name='feedbackCustomer',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='feedbackDriver',
        ),
        migrations.AddField(
            model_name='tripsession',
            name='tripcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='dropOffPoint',
            field=models.CharField(default=b'0000.00000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='pickUpPoint',
            field=models.CharField(default=b'0000.00000', max_length=30),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripOrderDateTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 8, 30, 37, 844255, tzinfo=utc)),
        ),
    ]
