# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20160504_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripsession',
            old_name='dateTimeTrip',
            new_name='datetimetrip',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='dropOffPoint',
            new_name='dropoffpoint',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='etaArrival',
            new_name='etaarrival',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='etaKM',
            new_name='etakm',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='etaTrip',
            new_name='etatrip',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='pickUpPoint',
            new_name='pickuppoint',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='timeConsumed',
            new_name='timeconsumed',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='tripStartDateTime',
            new_name='tripstartdatetime',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='tripOrderDateTime',
        ),
        migrations.AddField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 9, 55, 41, 869999, tzinfo=utc)),
        ),
    ]
