# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20160514_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(),
        ),
    ]
