# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_auto_20160525_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='dropoffpoint',
            field=models.CharField(default=b'0000.00000', max_length=25),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 23, 8, 37, 337675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripenddatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 23, 8, 37, 338576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 23, 8, 37, 338532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripstartdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 23, 8, 37, 338557, tzinfo=utc)),
        ),
    ]
