# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_auto_20160622_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tripdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 10, 19, 2, 799956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripenddatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 10, 19, 2, 800543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 10, 19, 2, 800508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripstartdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 10, 19, 2, 800526, tzinfo=utc)),
        ),
    ]
