# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_auto_20160622_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsession',
            name='datetimetrip',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
