# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_auto_20160624_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='tripsession',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='trip',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='customer_pays',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='triprequest',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.TripRequest'),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='etakm',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Fare',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
