# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_auto_20160805_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='requestedprice',
            field=models.FloatField(default=0.0),
        ),
    ]
