# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_auto_20160816_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='dropoffpoint',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='pickuppoint',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='dropoffpoint',
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='pickuppoint',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='dropoffLat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='dropoffLng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='pickupLat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='pickupLng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='dropoffLat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='dropoffLng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='pickupLat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='tripsession',
            name='pickupLng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
