# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_auto_20160918_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequest',
            old_name='dropoffLat',
            new_name='dropofflat',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='dropoffLng',
            new_name='dropofflng',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='pickupLat',
            new_name='pickuplat',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='pickupLng',
            new_name='pickuplng',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='dropoffLat',
            new_name='dropofflat',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='dropoffLng',
            new_name='dropofflng',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='pickupLat',
            new_name='pickuplat',
        ),
        migrations.RenameField(
            model_name='tripsession',
            old_name='pickupLng',
            new_name='pickuplng',
        ),
    ]
