# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_triprequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='dropofflat',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='dropofflng',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='pickuplat',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='pickuplng',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='datetimetrip',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='dropofflat',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='dropofflng',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='pickuplat',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='pickuplng',
            field=models.DecimalField(decimal_places=6, default=11.1111, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripenddatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripstartdatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
