# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_auto_20161007_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsession',
            name='datetimetrip',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 20, 23, 53, 677123)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripenddatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 20, 23, 53, 677257)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='triporderdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 20, 23, 53, 677196)),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='triprequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.TripRequest'),
        ),
        migrations.AlterField(
            model_name='tripsession',
            name='tripstartdatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 20, 23, 53, 677227)),
        ),
    ]
