# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0032_remove_tripsession_tripgraphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsession',
            name='tripgraphic',
            field=models.ImageField(null=True, upload_to=b'TripSessionGraphics/'),
        ),
    ]
