# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0033_tripsession_tripgraphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripGraphics',
            fields=[
                ('tripsession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trip.TripSession')),
                ('tripgraphic', models.ImageField(null=True, upload_to=b'TripSessionGraphics/')),
            ],
            options={
                'verbose_name': 'TripGraphic',
                'verbose_name_plural': 'TripGraphics',
            },
        ),
        migrations.RemoveField(
            model_name='tripsession',
            name='tripgraphic',
        ),
    ]
