# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0034_auto_20161031_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsession',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
