# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0035_tripsession_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsession',
            name='tripsessiongraphic',
            field=models.ImageField(default=b'default.png', upload_to=b'tripsession/'),
        ),
    ]
