# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_auto_20161114_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.FloatField(default=0.0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DriverDetails')),
            ],
            options={
                'verbose_name': 'Debt',
            },
        ),
    ]
