# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtcollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debttable',
            name='driver_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='debttable',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
